grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.rdevops74.online

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.rdevops74.online