grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.rdevopsb74.online

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.rdevopsb74.online